### ISSUE TITLE
make config file versions

### ISSUE THREAD

**Issue by rokde** [ipunkt/rancherize#13]
A config file should have a file version. If none given, version 1 is used.
Otherwise you have to give the config file a version for being backwards compatible.

Example:
```json
{
  "version": "2",
  "blueprints": {
```

**Comment by svensp** [comment]
The branch `config-version` now brings a new Interface `ConfigurationVersionService` which can be used to check the version given in the project rancherize.json
This is necessary because there is no global parser but a parser per plugin/module which don't necessarily take the full config as argument.

**Comment by svensp** [comment]
Included in 2.17.0
