### ISSUE TITLE
Missing .rancherize file in home directory throws exception

### ISSUE THREAD

**Issue by rokde** [ipunkt/rancherize#18]
It should be no problem when missing .rancherize in home directory. For local environment it is not necessary to have it.

```bash
[Rancherize\Configuration\Exceptions\GlobalConfigurationNotFoundException]  
File /home/USER/.rancherize not found.
```

It should ignore the missing file.

**Comment by svensp** [comment]
Can be tested in Branch `ignore-missing-global-config`.
I'm not sure I like this change as it increases the potential for first time users to be confused. Not having the necessary accounts set up will still cause a readable error but the information that setting the account should be done in ~/.rancherize is lost.

**Comment by justb81** [comment]
i think it is not the best implementation to not throw the exception. it would be better to only throw the exception if the account data is really needed to access docker/rancher and is still missing.

**Comment by svensp** [comment]
I think in this case it is. The global configuration will probably move forward to be loaded on all commands because it is _not_ meant to be solely for accounts. Thus it is perfectly acceptable for the file at this point not to exist.
The {Rancher,Docker}AccessConfigService are the actual binding point between the configuration on the {Rancher,Docker}AccessServices so it would instead make sense to extends the generic `AccountNotFoundException` with a `AccountNotFoundInConfiguration` Exception which then requests the user to run `rancher:access` to set them up

**Comment by svensp** [comment]
2.17.0 trials the error as specialized exception in the AccessConfigServices

**Comment by svensp** [comment]
Please test the usefulness of the implementation with the AccessService exceptions pointing towards the `rancher:access` command
