### ISSUE TITLE
Add custom services

### ISSUE THREAD

**Issue by justb81** [ipunkt/rancherize#27]
Often there is a need for a simple 3rd-party service to use in your application. Rancherize should have a possibility to include such services in `rancherize.json` and put them into `docker-compose.yml`.

**Comment by svensp** [comment]
For most cases it would be more beneficial to make a mini-plugin to add the 3rd-party service to rancherize to keep in line with the abstraction it provides - set `"mailtrap":{ "options": ... }` if you want mailtrap instead of specifing the image directly.
I heard the argument that it is necessary to add microservices from other projects for local development, this seems to make sense to me.

I'd split this into 2 parts:
- actual 3rd party services configured within rancherize
- Blueprint event to add mini services

Blueprint mini services: currently the blueprint has to know the plugin and actively use it. This is backwards for plugins, they should know a certain event where they get their data and do everything to be used with the main service created there.
Idea: `BlueprintBuiltEvent` with data
- Blueprint
- MainService
- Infrastructure
- Configuration
Read the configuration, add mini service to the infrastructure and add Links from the MainService. Maybe copy the Environment from the MainService.
